name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install System Libs
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev libappindicator3-dev
        sudo apt-get install libxcb-xfixes0-dev
        sudo apt-get install libxcb-shape0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose